name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y make
          python -m pip install -U pip setuptools wheel
          python -m pip install pytest
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Build (fixtures)
        shell: bash
        run: |
          set -euxo pipefail
          make all

      - name: Tests
        shell: bash
        run: |
          set -euxo pipefail
          python -m pytest -q

  gate:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "Gate passed"
