name: pages
on:
  push:
    branches: [main]
    paths: ["web/**","docs/**","receipts/**","qa/run_all.py",".github/workflows/pages.yml"]
  workflow_dispatch:
permissions: { contents: read, pages: write, id-token: write }
concurrency: { group: "pages", cancel-in-progress: true }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build site artifacts (ensure bundles.json exists)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest >/dev/null 2>&1 || true
          make bundles || true
          mkdir -p docs
          cp -r web/* docs/
          [ -f receipts/events.jsonl ] && cp receipts/events.jsonl docs/receipts.jsonl || true
      - uses: actions/upload-pages-artifact@v3
        with: { path: docs }
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
